import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import { resolve } from 'path';

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react()],
  optimizeDeps: {
    exclude: ['lucide-react'],
  },
  resolve: {
    alias: {
      '@loco-ui/button': resolve(__dirname, 'packages/button/src'),
      '@loco-ui/theme': resolve(__dirname, 'packages/theme/src'),
      '@loco-ui/icon': resolve(__dirname, 'packages/icon/src'),
      '@loco-ui/typography': resolve(__dirname, 'packages/typography/src'),
      '@loco-ui/link': resolve(__dirname, 'packages/link/src'),
      '@loco-ui/form': resolve(__dirname, 'packages/form/src'),
      '@loco-ui/inputfield': resolve(__dirname, 'packages/inputfield/src'),
      '@loco-ui/checkbox': resolve(__dirname, 'packages/checkbox/src'),
      '@loco-ui/radiobutton': resolve(__dirname, 'packages/radiobutton/src'),
      '@loco-ui/dropdownmenu': resolve(__dirname, 'packages/dropdownmenu/src'),
      '@loco-ui/switch': resolve(__dirname, 'packages/switch/src'),
      '@loco-ui/slider': resolve(__dirname, 'packages/slider/src'),
      '@loco-ui/autocomplete': resolve(__dirname, 'packages/autocomplete/src'),
      '@loco-ui/form-group': resolve(__dirname, 'packages/form-group/src'),
      '@loco-ui/label': resolve(__dirname, 'packages/label/src'),
      '@loco-ui/navbar': resolve(__dirname, 'packages/navbar/src'),
      '@loco-ui/sidebar': resolve(__dirname, 'packages/sidebar/src'),
      '@loco-ui/breadcrumb': resolve(__dirname, 'packages/breadcrumb/src'),
      '@loco-ui/pagination': resolve(__dirname, 'packages/pagination/src'),
      '@loco-ui/tabs': resolve(__dirname, 'packages/tabs/src'),
      '@loco-ui/drawer': resolve(__dirname, 'packages/drawer/src'),
      '@loco-ui/menu': resolve(__dirname, 'packages/menu/src'),
      '@loco-ui/stepper': resolve(__dirname, 'packages/stepper/src'),
      '@loco-ui/modal': resolve(__dirname, 'packages/modal/src'),
      '@loco-ui/tooltip': resolve(__dirname, 'packages/tooltip/src'),
      '@loco-ui/spinner': resolve(__dirname, 'packages/spinner/src'),
      '@loco-ui/alert': resolve(__dirname, 'packages/alert/src'),
      '@loco-ui/notification': resolve(__dirname, 'packages/notification/src'),
      '@loco-ui/toast': resolve(__dirname, 'packages/toast/src'),
      '@loco-ui/popover': resolve(__dirname, 'packages/popover/src'),
      '@loco-ui/skeleton': resolve(__dirname, 'packages/skeleton/src'),
      '@loco-ui/card': resolve(__dirname, 'packages/card/src'),
      '@loco-ui/accordion': resolve(__dirname, 'packages/accordion/src'),
      '@loco-ui/badge': resolve(__dirname, 'packages/badge/src'),
      '@loco-ui/avatar': resolve(__dirname, 'packages/avatar/src'),
      '@loco-ui/progress-bar': resolve(__dirname, 'packages/progress-bar/src'),
      '@loco-ui/table': resolve(__dirname, 'packages/table/src'),
      '@loco-ui/list': resolve(__dirname, 'packages/list/src'),
      '@loco-ui/tree-view': resolve(__dirname, 'packages/tree-view/src'),
      '@loco-ui/carousel': resolve(__dirname, 'packages/carousel/src'),
      '@loco-ui/tag': resolve(__dirname, 'packages/tag/src'),
      '@loco-ui/chip': resolve(__dirname, 'packages/chip/src'),
      '@loco-ui/rating': resolve(__dirname, 'packages/rating/src'),
      '@loco-ui/collapse': resolve(__dirname, 'packages/collapse/src'),
      '@loco-ui/timeline': resolve(__dirname, 'packages/timeline/src'),
      '@loco-ui/statistic': resolve(__dirname, 'packages/statistic/src'),
      '@loco-ui/container': resolve(__dirname, 'packages/container/src'),
      '@loco-ui/grid': resolve(__dirname, 'packages/grid/src'),
      '@loco-ui/row': resolve(__dirname, 'packages/row/src'),
      '@loco-ui/column': resolve(__dirname, 'packages/column/src'),
      '@loco-ui/footer': resolve(__dirname, 'packages/footer/src'),
      '@loco-ui/header': resolve(__dirname, 'packages/header/src'),
      '@loco-ui/divider': resolve(__dirname, 'packages/divider/src'),
      '@loco-ui/space': resolve(__dirname, 'packages/space/src'),
      '@loco-ui/portal': resolve(__dirname, 'packages/portal/src'),
      '@loco-ui/transition': resolve(__dirname, 'packages/transition/src'),
      '@loco-ui/scroll-to-top': resolve(__dirname, 'packages/scroll-to-top/src'),
      '@loco-ui/error-boundary': resolve(__dirname, 'packages/error-boundary/src'),

    }
  }
});